Repository paulahemsi/ft_containers, pull requests merged in 2022-04, with the labels that each got.

#128 Add next, previous, beging and end to btree
  containers/Map.hpp
  rb_tree/Makefile
  rb_tree/includes/btree.hpp
  rb_tree/includes/btree_auxiliary.tpp
  rb_tree/includes/btree_begin.tpp
  rb_tree/includes/btree_delete.tpp
  rb_tree/includes/btree_delete_rules.tpp
  rb_tree/includes/btree_end.tpp
  rb_tree/includes/btree_insert_data.tpp
  rb_tree/includes/btree_next.tpp
  rb_tree/includes/btree_previous.tpp
  rb_tree/includes/btree_search_item.tpp
  rb_tree/includes/compare.tpp
  rb_tree/includes/rb_tree.hpp
  rb_tree/tests/main.cpp
Labels: Iterators

#134 Find implemented
  containers/Map.hpp
  rb_tree/includes/rb_tree.hpp
  tests/map/find.cpp
  tests/map/main.cpp
  tests/map/tests.hpp
  tests/map/utils.cpp
  tests/mk/map_srcs.mk
Labels: Public Member Functions, Tests

#135 get allocator
  containers/Map.hpp
  tests/map/get_allocator.cpp
  tests/map/main.cpp
  tests/map/tests.hpp
  tests/mk/map_srcs.mk
Labels: Public Member Functions

#139 erase
  containers/Map.hpp
  rb_tree/includes/btree_delete.tpp
  rb_tree/includes/btree_previous.tpp
  rb_tree/includes/rb_tree.hpp
  tests/map/erase.cpp
  tests/map/find.cpp
  tests/map/main.cpp
  tests/map/tests.hpp
  tests/mk/map_srcs.mk
Labels: Public Member Functions, Modifier

#142 upper_bound and lower_bound
  containers/Map.hpp
  tests/map/lower_bound.cpp
  tests/map/main.cpp
  tests/map/tests.hpp
  tests/map/upper_bound.cpp
  tests/mk/map_srcs.mk
Labels: Public Member Functions, Operations

#147 insert with hint
  containers/Map.hpp
  iterators/map_iterator.hpp
  rb_tree/includes/btree_insert_data.tpp
  tests/map/insert.cpp
Labels: Public Member Functions, Modifier

#148 Empty method
  containers/Map.hpp
  tests/map/empty.cpp
  tests/map/main.cpp
  tests/map/tests.hpp
Labels: Public Member Functions, Capacity

#158 map(operators): implement equality operators
  containers/Map.hpp
  tests/map/equality_operator.cpp
  tests/map/main.cpp
  tests/map/tests.hpp
  tests/mk/map_srcs.mk
Labels: Non-Member Function

#160 less than
  aux_templates/lexicographical_compare.tpp
  containers/Map.hpp
  tests/map/equal_range.cpp
  tests/map/less-than_comparison.cpp
  tests/map/lower_bound.cpp
  tests/map/main.cpp
  tests/map/tests.hpp
  tests/map/upper_bound.cpp
  tests/mk/map_srcs.mk
Labels: Non-Member Function

#159 test(map): extract iterators test from main
  tests/map/iterator.cpp
  tests/map/main.cpp
  tests/map/tests.hpp
  tests/mk/map_srcs.mk
Labels: Iterators

#178 operators overloads
  containers/Stack.hpp
  tests/mk/stack_srcs.mk
  tests/stack/equality_operator.cpp
  tests/stack/less-than_comparison.cpp
  tests/stack/main.cpp
  tests/stack/pop.cpp
  tests/stack/tests.hpp
Labels: Non-Member Function

#184 stack(test): add different underlying containers
  tests/stack/empty.cpp
  tests/stack/equality_operator.cpp
  tests/stack/less-than_comparison.cpp
  tests/stack/pop.cpp
  tests/stack/push.cpp
  tests/stack/size.cpp
  tests/stack/top.cpp
Labels: Tests

#189 improve swap tests
  tests/vector/non-member_functions/swap.cpp
  tests/vector/non-member_functions/swap.tpp
Labels: Tests
